version: '2'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3306:3306"
  ipam:
    depends_on:
      - mysql
    image: pierrecdn/phpipam:1.3
    environment:
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "80:80"
  selenium:
    depends_on:
      - ipam
    image: selenium/standalone-chrome:3.8.1-bohrium
    ports:
      - "4444:4444"
      - "5900:5900"
    privileged: true
    volumes:
    - /dev/shm:/dev/shm
  phpipam_pyclient:
    command: /bin/bash
    image: registry.gitlab.com/viniciusarcanjo/phpipam-pyclient:dev
    stdin_open: true
    tty: true
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    volumes:
      - .:/app
